[build]
  publish = "."
  command = ""

[build.environment]
  NODE_VERSION = "18"

# Headers for better security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net https://unpkg.com https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://api.modrinth.com; font-src 'self' data:;"

# Cache static assets
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Redirect rules for SPA-like behavior (if needed)
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 404

# Custom domain redirect to ensure all traffic goes to your custom domain
[[redirects]]
  from = "https://*.netlify.app/*"
  to = "https://mcmodupdate.app/:splat"
  status = 301
  force = true 