name: 🐌 Performance Issue
description: Report slow processing, timeouts, or performance problems
title: "[Performance]: "
labels: ["performance", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Experiencing slow performance or timeouts? This template will help us identify and fix performance issues.
        
        Please provide as much detail as possible about the performance problem you're experiencing.

  - type: checkboxes
    id: preliminary-checks
    attributes:
      label: Preliminary Checks
      description: Please confirm the following before proceeding
      options:
        - label: I have tried refreshing the page and the issue persists
          required: true
        - label: I have checked my internet connection is stable
          required: true
        - label: I have searched for existing performance-related issues
          required: true

  - type: dropdown
    id: performance-type
    attributes:
      label: Type of Performance Issue
      description: What kind of performance problem are you experiencing?
      options:
        - Slow file upload/processing
        - Page loading slowly
        - Interface feels unresponsive
        - Download generation takes too long
        - Browser freezes or becomes unresponsive
        - Timeout errors
        - Other (please specify in description)
    validations:
      required: true

  - type: textarea
    id: performance-description
    attributes:
      label: Performance Issue Description
      description: Describe the performance problem in detail
      placeholder: |
        - What specific action is slow?
        - How long does it take vs. what you'd expect?
        - Does it happen consistently or only sometimes?
    validations:
      required: true

  - type: textarea
    id: file-details
    attributes:
      label: File Information
      description: Details about the file(s) you're processing
      placeholder: |
        - File type: .jar / .mrpack / .zip
        - File size: (e.g., 50MB, 200MB, 1GB)
        - Number of mods: (if applicable)
        - Minecraft version: 
        - Mod platform: Fabric/Forge/NeoForge/Quilt
    validations:
      required: true

  - type: dropdown
    id: when-occurs
    attributes:
      label: When Does This Occur?
      description: At what stage do you experience the performance issue?
      options:
        - During file upload
        - While analyzing/processing the file
        - When generating the download
        - During page load/startup
        - Throughout the entire process
        - Other (please specify in description)
    validations:
      required: true

  - type: input
    id: approximate-time
    attributes:
      label: Approximate Time Taken
      description: How long does the slow operation take?
      placeholder: e.g., "5 minutes", "never completes", "30+ seconds"
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: What browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other (please specify in additional context)
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: Browser Version
      description: What version of your browser are you using?
      placeholder: e.g., Chrome 120.0.6099.109

  - type: dropdown
    id: device-type
    attributes:
      label: Device Type
      description: What type of device are you using?
      options:
        - Desktop/Laptop
        - Mobile Phone
        - Tablet
        - Other
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows
        - macOS
        - Linux
        - Android
        - iOS
        - Other (please specify in additional context)
    validations:
      required: true

  - type: textarea
    id: system-specs
    attributes:
      label: System Specifications (if known)
      description: Hardware specs that might be relevant
      placeholder: |
        - RAM: (e.g., 8GB, 16GB)
        - CPU: (e.g., Intel i5, M1 Mac, etc.)
        - Internet speed: (if known)
        - Any other relevant hardware info

  - type: textarea
    id: console-info
    attributes:
      label: Browser Console Information
      description: Any performance warnings or errors in browser console (F12 → Console)
      placeholder: |
        Check browser console (F12) for:
        - Performance warnings
        - Memory usage alerts
        - Network timeout errors
        - Any red error messages during the slow operation
      render: text

  - type: dropdown
    id: reproducibility
    attributes:
      label: How Consistently Does This Happen?
      description: Can you reproduce this performance issue?
      options:
        - Always - happens every time
        - Usually - happens most of the time
        - Sometimes - happens occasionally  
        - Rarely - only happened once or twice
        - Only with specific files
    validations:
      required: true

  - type: textarea
    id: comparison
    attributes:
      label: Comparison with Other Files
      description: Do other files process normally, or is everything slow?
      placeholder: |
        - Do smaller files process faster?
        - Have you tried different file types?
        - Is this specific to certain mod platforms?

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might help diagnose the performance issue
      placeholder: |
        - Network conditions (WiFi, mobile data, corporate network, etc.)
        - Time of day when this occurs
        - Other applications running
        - Any browser extensions that might interfere
        - Screenshots of performance metrics (if available) 